Add translator example
pynecone-io/pynecone-examples pull request #1
Opened 2022-11-16 11:36 UTC by kbrgl

Adds a translator app to the examples. The app enables you to translate text and post the translation as a message.

2022-11-16 11:58 UTC, kbrgl commented
![image](https://user-images.githubusercontent.com/13417496/202174899-42b25df7-f659-4b55-b214-fc8643b10399.png)

2022-11-16 12:01 UTC, kbrgl commented
https://user-images.githubusercontent.com/13417496/202175352-62c27373-ead8-4b09-a9dd-484f69ec55e6.mov

2022-11-16 19:55 UTC, picklelo commented on translator/translator/translator.py
> +def output():
This looks sick!!

2022-11-16 20:05 UTC, picklelo requested changes
Looks good, just a couple comments

2022-11-16 20:05 UTC, picklelo commented on translator/translator/translator.py
> +            on_change=State.set_text,
We should probably make this `on_blur` for performance reasons (or add some sort of debouncing logic). If they type fast it acts strange.

2022-11-16 20:05 UTC, picklelo commented on translator/translator/translator.py
> +class Message(Base):
Maybe we include the original text, as well as the language here.

2022-11-16 20:05 UTC, picklelo commented on translator/translator/translator.py
> +    return pc.box(
Let's make this a `pc.container` to center it.

2022-11-23 19:24 UTC, picklelo requested changes
Thanks for the updates, just one comment about updating the config file to the latest format.

2022-11-23 19:24 UTC, picklelo commented on translator/translator/translator.py
> +    return pc.box(
We could also use a `pc.icon` here: https://pynecone.io/docs/library/media/icon

2022-11-23 19:24 UTC, picklelo commented on translator/pcconfig.py
> +# The Pynecone configuration file.
We recently updated the config format - could you update this?

You'll need to
1. delete this `pcconfig.py` file
2. run `pc init`with the latest version of Pynecone (pip 0.1.5 or the latest git). It should regenerate this file and look something like this:
```
import pynecone as pc

config = pc.Config(
    app_name="translator",
)
```
3. Running `pc init` after deleting the config file will replace your app code with the template app, you should be able to do `git checkout translator` to get the code back in the main folder.

2022-11-24 19:34 UTC, picklelo approved these changes
LGTM!

2022-11-24 19:53 UTC, merged