chatroom: State._process is an async generator
pynecone-io/pynecone-examples pull request #124
Opened 2023-06-28 23:26 UTC by masenf

use `async for` construct when iterating through state updates generated from processing events.

use form and on_submit to get easy enter-button send functionality

2023-06-29 04:31 UTC, milochen0418 commented
It works 
<img width="1432" alt="Screenshot 2023-06-29 at 12 31 06 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/d7bc4967-2373-483e-82f2-ddd25be28b69">

2023-06-29 04:32 UTC, milochen0418 approved these changes
<img width="1432" alt="Screenshot 2023-06-29 at 12 31 06 PM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/878f33b5-d0fc-4c26-bf5d-69f64106eada">
It works ~

2023-06-29 04:41 UTC, milochen0418 approved these changes

2023-07-01 13:45 UTC, Lendemor commented on chatroom/requirements.txt
should pass it to reflex>=0.2.0

2023-07-01 13:46 UTC, Lendemor requested changes

2023-07-01 13:46 UTC, Lendemor commented on chatroom/chatroom/chatroom.py
let's pass it on reflex too and use `rx.`

2023-07-01 15:55 UTC, masenf commented on chatroom/chatroom/chatroom.py
done

2023-07-02 14:42 UTC, milochen0418 approved these changes

2023-07-06 14:27 UTC, Lendemor approved these changes

2023-07-06 14:27 UTC, merged